version: '2.3'

services:

  demogrid:
    image: demogrid
    container_name: demogrid
    working_dir: /data
    build:
      context: ../
      dockerfile: docker/Dockerfile

    environment:
      - PYTHONPATH=/data
      # - DISPLAY=unix$DISPLAY
    ports:
      - 6009:6006
    volumes:
      - ../:/data
      # - ../../GAMES_GIFS/:/gifs
      # - /tmp/.X11-unix:/tmp/.X11-unix

    runtime: nvidia
    command: tail /dev/null -f
